# Generated by Django 5.1 on 2024-08-13 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='Изоображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название вещи')),
                ('brand', models.CharField(max_length=255, verbose_name='Брэнд')),
                ('discount', models.IntegerField(default=None, null=True, verbose_name='Скидка')),
                ('image', models.ImageField(upload_to='photos/', verbose_name='Изоображение')),
                ('size', models.CharField(max_length=255, null=True, verbose_name='Размеры')),
                ('price', models.IntegerField(null=True, verbose_name='Цена')),
                ('thing_slug', models.SlugField(max_length=255, unique=True, verbose_name='Слаг Вещей')),
                ('cat', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.PROTECT, to='camicetta.category')),
            ],
            options={
                'verbose_name': 'Вещь',
                'verbose_name_plural': 'Вещи',
                'ordering': ['id'],
            },
        ),
    ]
