# Generated by Django 2.2.19 on 2024-08-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camicetta', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='discount',
            field=models.IntegerField(default=0, null=True, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),

    ]
