# Generated by Django 2.2.19 on 2024-08-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camicetta', '0002_auto_20240817_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Размеры'),
        ),
    ]
